"""empty message

Revision ID: 22dc522c1d26
Revises: 89e16ee2bbf0
Create Date: 2025-06-21 11:28:42.671742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22dc522c1d26'
down_revision = '89e16ee2bbf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.ENUM('admin', 'teacher', 'student', 'parent'), nullable=False))
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('active')

    # ### end Alembic commands ###
