"""empty message

Revision ID: 3570bc9b2892
Revises: b78da8cf9848
Create Date: 2025-09-09 23:21:34.647148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3570bc9b2892'
down_revision = 'b78da8cf9848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('randomname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('randomname', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
