"""empty message

Revision ID: 4b9c33b8f31d
Revises: dc0fca9eb232
Create Date: 2025-06-28 23:43:45.421942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b9c33b8f31d'
down_revision = 'dc0fca9eb232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_class_section_session', ['name', 'section', 'session_id'])

    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_rollno_class', ['roll_number', 'class_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rollno_class', type_='unique')

    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_constraint('uq_class_section_session', type_='unique')

    # ### end Alembic commands ###
