"""empty message

Revision ID: 4cade9510dad
Revises: 
Create Date: 2025-09-02 19:16:01.636503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cade9510dad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_encoding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encoding_hash', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint('_student_face_uc', ['student_id', 'encoding_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_encoding', schema=None) as batch_op:
        batch_op.drop_constraint('_student_face_uc', type_='unique')
        batch_op.drop_column('encoding_hash')

    # ### end Alembic commands ###
