"""empty message

Revision ID: 9e9ec2165931
Revises: a102fca1d21d
Create Date: 2025-07-28 22:12:24.525425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e9ec2165931'
down_revision = 'a102fca1d21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('teacher_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('teacher_ibfk_2'), 'subject', ['subject_id'], ['id'])

    # ### end Alembic commands ###
