"""empty message

Revision ID: dc0fca9eb232
Revises: 
Create Date: 2025-06-28 20:09:42.323893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc0fca9eb232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apaar_id', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['apaar_id'])

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['code'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('apaar_id')

    # ### end Alembic commands ###
